ajax:
    path:     /ajax/{subject}
    defaults: { _controller: silabos\Controller\HomeController::ajaxAction }
    methods:  [POST]
index:
    path:     /
    defaults: { _controller: silabos\Controller\HomeController::indexAction }
silabos_files:
    path:     /archivos/{silaboId}
    defaults: { _controller: inidate\Controller\HomeController::filesAction , silaboId: 0}
    methods:  [GET]    