ajax:
    path:     /ajax/{subject}
    defaults: { _controller: silabos\Controller\HomeController::ajaxAction }
    methods:  [POST]
index:
    path:     /
    defaults: { _controller: silabos\Controller\HomeController::indexAction }